title = "Future Web"
baseURL = "/"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://facebook.com"
  twitter = "https://twitter.com/GoHugoIO"
  instagram = "https?//instagram.com"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2

[menu]
  [[menu.main]]
    name = "All memes"
    url = "posts"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "about"
  [[meun.main]]
    name = "Contact"
    url = "contact"